# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoChat',
            fields=[
                ('id_chat', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrechat', models.CharField(max_length=200, null=True)),
                ('is_suscrito_actu', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=200)),
                ('url_imagen', models.CharField(max_length=200)),
                ('textobuscado', models.CharField(max_length=200)),
                ('ruta_imagen', models.CharField(max_length=200)),
                ('id_lista', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_u', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=b'NoName', max_length=200)),
                ('apellido', models.CharField(max_length=200, null=True)),
                ('nombreusuario', models.CharField(max_length=200, null=True)),
                ('is_suscrito_actu', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaServidor',
            fields=[
                ('usuario_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BotTelegram.Usuario')),
                ('fecha', models.DateTimeField()),
                ('imagen_enviada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotTelegram.Imagen')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BotTelegram.RespuestaServidor'),
        ),
    ]
