# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BotTelegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosImagenBorrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_text', models.CharField(default=b'Upper TEXT', max_length=200, null=True)),
                ('lower_text', models.CharField(default=b'Lower TEXT', max_length=200, null=True)),
                ('color', models.CharField(default=b'Red', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='datos_imagen_borrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BotTelegram.DatosImagenBorrador'),
        ),
    ]
