# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BotTelegram', '0002_auto_20161005_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultima_respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BotTelegram.RespuestaServidor'),
        ),
    ]
