# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotTelegram', '0002_auto_20161010_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='comando_en_espera',
            field=models.CharField(default=b'None', max_length=200),
        ),
    ]
