# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotTelegram', '0003_auto_20161005_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupochat',
            old_name='suscrito_actu',
            new_name='is_suscrito_actu',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='suscrito_actu',
            new_name='is_suscrito_actu',
        ),
        migrations.AddField(
            model_name='imagen',
            name='title',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
