# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BotTelegram', '0003_usuario_comando_en_espera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrupoChat',
        ),
        migrations.RemoveField(
            model_name='respuestaservidor',
            name='imagen_enviada',
        ),
        migrations.RemoveField(
            model_name='respuestaservidor',
            name='usuario_t',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultima_respuesta',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_ultima_respuesta',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BotTelegram.Imagen'),
        ),
        migrations.AlterField(
            model_name='datosimagenborrador',
            name='color',
            field=models.CharField(default=b'white', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='id_lista',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='RespuestaServidor',
        ),
    ]
