# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotTelegram', '0004_auto_20161006_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaservidor',
            name='id_mensaje',
        ),
        migrations.AddField(
            model_name='respuestaservidor',
            name='id',
            field=models.AutoField(auto_created=True,  primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
