# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotTelegram', '0004_auto_20161106_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='datos_imagen_borrador',
        ),
        migrations.AddField(
            model_name='usuario',
            name='color',
            field=models.CharField(default=b'white', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='esta_creando_meme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lower_text',
            field=models.CharField(default=b'Lower TEXT', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='upper_text',
            field=models.CharField(default=b'Upper TEXT', max_length=200),
        ),
        migrations.DeleteModel(
            name='DatosImagenBorrador',
        ),
    ]
